### ISSUE TITLE
Check or document artifact bucket must have versioning enabled to publish future versions

### ISSUE THREAD

**Issue by jwilson8767** [transcend-io/terraform-aws-lambda-at-edge#10]
Because deploying changes requires the aws_lambda_function resources `s3_object_version` to update, the artifact bucket should have versioning enabled, otherwise the version is always "1" and no function updates are published. Please either add a check to ensure artifacts will be versioned appropriately, or at least document this requirement.

**Comment by dmattia** [comment]
Added documentation for this in the top level README.md, thanks!
